name: Compile Library

on:
  push:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - 'examples/**'
  pull_request:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - 'examples/**'

jobs:
  esp32:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: 
          - "esp32dev"
          - "lolin32"
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Install library
      run: | 
        pio lib -g install \
        https://github.com/mobizt/ReadyMail


    - name: Create main file
      run: |
        echo "#include <Arduino.h>" >> src/main.cpp
        echo "#include <WiFi.h>" >> src/main.cpp
        echo "#include <WiFiClientSecure.h>" >> src/main.cpp
        echo "#define ENABLE_IMAP" >> src/main.cpp
        echo "#define ENABLE_SMTP" >> src/main.cpp
        echo "#define ENABLE_DEBUG" >> src/main.cpp
        echo "#include <ReadyMail.h>" >> src/main.cpp
        echo "WiFiClientSecure ssl_client;" >> src/main.cpp
        echo "SMTPClient smtp(ssl_client);" >> src/main.cpp
        echo "IMAPClient imap(ssl_client);" >> src/main.cpp
        echo "void setup() {" >> src/main.cpp
        echo "ssl_client.setInsecure();" >> src/main.cpp
        echo "smtp.connect(\"smtp.gmail.com\", 465, \"127.0.0.1\", NULL);" >> src/main.cpp
        echo "imap.connect(\"imap.gmail.com\", 993, NULL);" >> src/main.cpp
        echo "}" >> src/main.cpp

        echo "void loop() {}" >> src/main.cpp

    - name: Run PlatformIO
      run: pio ci --board=${{ matrix.board }} src

  esp8266:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: 
          - "d1_mini"
          - "nodemcuv2"
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Install library
      run: | 
        pio lib -g install \
        https://github.com/mobizt/ReadyMail


    - name: Create main file
      run: |
        echo "#include <Arduino.h>" >> src/main.cpp
        echo "#include <ESP8266WiFi.h>" >> src/main.cpp
        echo "#include <WiFiClientSecure.h>" >> src/main.cpp
        echo "#define ENABLE_IMAP" >> src/main.cpp
        echo "#define ENABLE_SMTP" >> src/main.cpp
        echo "#define ENABLE_DEBUG" >> src/main.cpp
        echo "#include <ReadyMail.h>" >> src/main.cpp
        echo "WiFiClientSecure ssl_client;" >> src/main.cpp
        echo "SMTPClient smtp(ssl_client);" >> src/main.cpp
        echo "IMAPClient imap(ssl_client);" >> src/main.cpp
        echo "void setup() {" >> src/main.cpp
        echo "ssl_client.setInsecure();" >> src/main.cpp
        echo "smtp.connect(\"smtp.gmail.com\", 465, \"127.0.0.1\", NULL);" >> src/main.cpp
        echo "imap.connect(\"imap.gmail.com\", 993, NULL);" >> src/main.cpp
        echo "}" >> src/main.cpp

        echo "void loop() {}" >> src/main.cpp

    - name: Run PlatformIO
      run: pio ci --board=${{ matrix.board }} src

  mkrwifi1010:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: 
          - "mkrwifi1010"
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Install library
      run: | 
        pio lib -g install \
        https://github.com/mobizt/ReadyMail


    - name: Create main file
      run: |
        echo "#include <Arduino.h>" >> src/main.cpp
        echo "#include <WiFi.h>" >> src/main.cpp
        echo "#include <WiFiNINA.h>" >> src/main.cpp
        echo "#include <WiFiSSLClient.h>" >> src/main.cpp
        echo "#define ENABLE_IMAP" >> src/main.cpp
        echo "#define ENABLE_SMTP" >> src/main.cpp
        echo "#define ENABLE_DEBUG" >> src/main.cpp
        echo "#include <ReadyMail.h>" >> src/main.cpp
        echo "WiFiSSLClient ssl_client;" >> src/main.cpp
        echo "SMTPClient smtp(ssl_client);" >> src/main.cpp
        echo "IMAPClient imap(ssl_client);" >> src/main.cpp
        echo "void setup() {" >> src/main.cpp
        echo "ssl_client.setInsecure();" >> src/main.cpp
        echo "smtp.connect(\"smtp.gmail.com\", 465, \"127.0.0.1\", NULL);" >> src/main.cpp
        echo "imap.connect(\"imap.gmail.com\", 993, NULL);" >> src/main.cpp
        echo "}" >> src/main.cpp

        echo "void loop() {}" >> src/main.cpp

    - name: Run PlatformIO
      run: pio ci --board=${{ matrix.board }} src

  picow:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Create main file
      run: |
        echo "#include <Arduino.h>" >> src/main.cpp
        echo "#include <WiFi.h>" >> src/main.cpp
        echo "#include <WiFiClientSecure.h>" >> src/main.cpp
        echo "#define ENABLE_IMAP" >> src/main.cpp
        echo "#define ENABLE_SMTP" >> src/main.cpp
        echo "#define ENABLE_DEBUG" >> src/main.cpp
        echo "#include <ReadyMail.h>" >> src/main.cpp
        echo "WiFiClientSecure ssl_client;" >> src/main.cpp
        echo "SMTPClient smtp(ssl_client);" >> src/main.cpp
        echo "IMAPClient imap(ssl_client);" >> src/main.cpp
        echo "void setup() {" >> src/main.cpp
        echo "ssl_client.setInsecure();" >> src/main.cpp
        echo "smtp.connect(\"smtp.gmail.com\", 465, \"127.0.0.1\", NULL);" >> src/main.cpp
        echo "imap.connect(\"imap.gmail.com\", 993, NULL);" >> src/main.cpp
        echo "[env:rpipicow]" >> platformio.ini
        echo "platform = https://github.com/maxgerhardt/platform-raspberrypi.git" >> platformio.ini
        echo "board = rpipicow" >> platformio.ini
        echo "framework = arduino" >> platformio.ini
        echo "board_build.core = earlephilhower" >> platformio.ini


    - name: Run PlatformIO
      run: pio ci --project-conf="platformio.ini" src
