name: Compile Library

on:
  push:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - 'examples/**'
  pull_request:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - 'examples/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: 
          - "d1_mini"
          - "nodemcuv2"
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio


    - name: Create main file
      run: |
        echo "#include <Arduino.h>" >> src/main.cpp
        echo "#include <ESP8266WiFi.h>" >> src/main.cpp
        echo "#include <WiFiClientSecure.h>" >> src/main.cpp
        echo "#include <ReadyMail.h>" >> src/main.cpp
        echo "WiFiClientSecure ssl_client;" >> src/main.cpp
        echo "SMTPClient smtp(ssl_client);" >> src/main.cpp
        echo "void setup() {" >> src/main.cpp
        echo "ssl_client.setInsecure();" >> src/main.cpp
        echo "smtp.connect(\"\", 465, \"127.0.0.1\", NULL);" >> src/main.cpp
        echo "}" >> src/main.cpp

        echo "void loop() {}" >> src/main.cpp

    - name: Run PlatformIO
      run: pio ci --board=${{ matrix.board }} src
